### ISSUE TITLE
Agricultural Lands and Drainage - wrong and missing information

### ISSUE THREAD

**Issue by francisdavey** [ministryofjustice/courtfinder#244]
Under A-Z for court finder:

https://courttribunalfinder.service.gov.uk/courts/F

There is a line for Agricultural Lands and Drainage, linking to:

https://courttribunalfinder.service.gov.uk/courts/first-tier-tribunal-property-chamber-agricultural-lands-and-drainage

which says (incorrectly) that there is no such court/tribunal, contradicting:

https://www.gov.uk/agricultural-land-and-drainage-disputes-apply-to-a-tribunal

Pedantically there's only one "Property Chamber" for the FTT and there aren't different sub-tribunals, but from an organisational and jurisdictional perspective there are (and the judiciary are ticketed separately). Certainly more useful information could be given.

**Comment by leoapost** [comment]
I'm closing this issue, as it's not relevant anymore.
