### ISSUE TITLE
Take one-time setup tasks out of run.sh

### ISSUE THREAD

**Issue by aldavidson** [ministryofjustice/courtfinder#261]
We currently run one-time setup tasks -

```
rake import:all
rake assets:precompile
```

..in the run.sh, which means they'll be run every time the container is started. This could cause painfully slow startup times and data corruption, as the import is based on csv files checked into the repo which will not match the state of the db.

We should move these out of run.sh and into a separate setup script (or similar)

**Comment by leoapost** [comment]
I'm closing this issue, as it's not relevant anymore.
